In [4]:
import numpy as np
arry_1 = np.array([6,10,11,1])
print(arry_1)
print(type(arry_1))

[ 6 10 11  1]
<class 'numpy.ndarray'>


In [14]:
import numpy as np

arry_1 = np.array([5,6,8,9,10])
arry_2 = np.array([20,30,40,50,60])

sum_arry = arry_1+arry_2
print(sum_arry)
result_subtraction = arry_2-arry_1
print("subtraction",result_subtraction)

result_multiplication = arry_1*arry_2
print("multiplication",result_multiplication)

result_division = arry_2/arry_1
print("division",result_division)

arry = arry_1**2
print(arry)

#square root
result_sqrt = np.sqrt(arry_1)
print(result_sqrt)

#summation
result_sum = np.sum(arry_1)
print(result_sum)

#mean Average
result_mean = np.mean(arry_1)
print(result_mean)

#max
result_max = np.max(arry_1)
print(result_max)

#min
result_min = np.min(arry_1)
print(result_min)

[25 36 48 59 70]
subtraction [15 24 32 41 50]
multiplication [100 180 320 450 600]
division [4.         5.         5.         5.55555556 6.        ]
[ 25  36  64  81 100]
[2.23606798 2.44948974 2.82842712 3.         3.16227766]
38
7.6
10
5


In [24]:
# arrays
import numpy as np
# 2d array
arry_1 = np.array([[1,3,5],[5,7,9]])
print(arry_1)
print(arry_1.shape)
print(arry_1.size)
print(arry_1.ndim)
print(arry_1.dtype)

# 3d array
arry_2 = np.array([[[1,3,5],[5,7,9]],[[3,5,7],[5,7,9]]])
print("2d array",arry_2)
print(arry_2.shape)
print(arry_2.size)
print(arry_2.ndim)
# array eke eliment wl type eka
print(arry_2.dtype)


[[1 3 5]
 [5 7 9]]
(2, 3)
6
2
int64
2d array [[[1 3 5]
  [5 7 9]]

 [[3 5 7]
  [5 7 9]]]
(2, 2, 3)
12
3
int64


In [27]:
# array indexing
# 1d array
arry_1 = np.array([3,5,7,9])
print(arry_1[2])

# 2d array
arry_2 = np.array([[2,4,6,8],[4,6,8,9]])
print(arry_2[1,1])

7
6


In [31]:
# task 01
# create a 2  numpy array with the shape 4by5 ontaitn in to numbers 1 to 20
#forfome the following array abou mactrict 
#add 10 to avery eliment
# multify every eliment by 2
#calculate the squre of each element

import numpy as np

array_1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(array_1)

array_2 = array_1 + 10
print(array_2)

array_3 = array_1 * 2
print("multify every eliment",array_3)

array_4 = array_1 ** 2
print("squre of each element",array_4)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
multify every eliment [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]
squre of each element [[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]]


In [34]:
#Boolean indexing 
arr = np.array([10,20,30,40,50])
condition = arr>25
print(condition)
# imposing boolean array -return the true values
result_array = arr[condition]
print(result_array)



[False False  True  True  True]
[30 40 50]


In [35]:
arr = np.array([10,20,30,40,50])
filter_array =arr [arr>25]
print(filter_array)

[30 40 50]


In [39]:
##multiple condition boolean array 
arr = np.array([10,20,30,40,50])
filter_array =arr [(arr>20) &(arr<50)]
print(filter_array)

filter_array1 =arr [(arr>20)|(arr==50)]
print(filter_array1)

[30 40]
[30 40 50]


In [41]:
#task02
#create  1d num py array with values from 1 to 20
#use boolean indexing o extract all even number


import numpy as np
array_1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(array_1[array_1 %2 == 0])


[ 2  4  6  8 10 12 14 16 18 20]


In [44]:
# task 3
#given thenum py array element 10,20,30,40,50, use boolean indexing to extract all element graterthan the mean of the array

import numpy as np
array_2 = np.array([10,20,30,40,50])
arr = np.mean(array_2)
print(arr)
print(array_2[array_2>arr])

30.0
[40 50]


In [54]:
#array initialization
#method zeros
#1d array
print(np.zeros(5))

# 2d array -pass the tuple
print(np.zeros((2,3)))
#dtype set
print(np.zeros((2,3),dtype = int))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]


In [56]:
#method full
print(np.full(8,10))

[10 10 10 10 10 10 10 10]


In [63]:
#task04
print(np.full((3,4),7))

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [64]:
#grabage values set this array
# manualy value assing krnwt wata speed up
print(np.empty((2,3)))

[[3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323]]


In [81]:
#pandas

import pandas as pd
data = {'Name':['Alina','Bod','David','Till'],'Age': [25,30,35,40]}
df = pd.DataFrame(data)
print(df)
print(type(df))
#row indexing change krnn puluwn
#lable base
print(df.loc[1,"Name"])
#index base
print(df.iloc[1,0])
#print row
print(df.loc[2])
#print 0,3 row data
print(df.iloc[[0,3]])
print(df.loc[[0,3]])


    Name  Age
0  Alina   25
1    Bod   30
2  David   35
3   Till   40
<class 'pandas.core.frame.DataFrame'>
Bod
Bod
Name    David
Age        35
Name: 2, dtype: object
    Name  Age
0  Alina   25
3   Till   40
    Name  Age
0  Alina   25
3   Till   40


In [111]:
import pandas as pd
data = {"colories":[340,500,590],"duration":[20,30,40]}
df = pd.DataFrame(data,index=["day1","day2","day3"])
print(df)
print(df.loc["day1","duration"])

print(df.loc["day2","colories"])
print(df.loc["day3","colories"])
print(df.iloc[2,0])
print(df.loc["day2"])
print(df.iloc[2])

#print colom
print("print colom",df["colories"])
print(df["duration"])

      colories  duration
day1       340        20
day2       500        30
day3       590        40
20
500
590
590
colories    500
duration     30
Name: day2, dtype: int64
colories    590
duration     40
Name: day3, dtype: int64
print colom day1    340
day2    500
day3    590
Name: colories, dtype: int64
day1    20
day2    30
day3    40
Name: duration, dtype: int64


In [169]:
import pandas as pd
df = pd.DataFrame({"A":[1,2,3,4,5],"B":[2,3,4,6,7]})
print(df.shape)
print(df.size)
print(df.dtypes)
#index object
print(df.columns)
#convert list
print(list(df.columns))
#value - converting numpy array -2d array
arr = df.values
print(arr)
print(type(arr))
print("=============")
# add new row
#len(df) - index ek data row eke set wenn one replace we
df.loc[len(df)] = [5,6]
print(df)
print("=============")
df.loc[3] = [45,67]
print(df)
print("================")
# col/row drop
#lables = remove krn col name ek
# axis - row ekd col ekk d blgnn (1-col,0-row)
remove = df.drop("B",axis=1,inplace=False)
print(remove)
print("=====================")

remove = df.drop(1,axis=0,inplace=False)
print(remove)

(5, 2)
10
A    int64
B    int64
dtype: object
Index(['A', 'B'], dtype='object')
['A', 'B']
[[1 2]
 [2 3]
 [3 4]
 [4 6]
 [5 7]]
<class 'numpy.ndarray'>
   A  B
0  1  2
1  2  3
2  3  4
3  4  6
4  5  7
5  5  6
    A   B
0   1   2
1   2   3
2   3   4
3  45  67
4   5   7
5   5   6
    A
0   1
1   2
2   3
3  45
4   5
5   5
    A   B
0   1   2
2   3   4
3  45  67
4   5   7
5   5   6


In [132]:
#function
#return row count
import pandas as pd
df = pd.DataFrame({"Age":[19,28,37],"salary":[2000,3000,4000]})
print(df)
print(len(df))
print(df.mean())
#catch the colom mean
print(df["Age"].mean())
#sum
print(df.sum())

   Age  salary
0   19    2000
1   28    3000
2   37    4000
3
Age         28.0
salary    3000.0
dtype: float64
28.0
Age         84
salary    9000
dtype: int64


In [146]:
#task6
#you are the data analacy fora details company the company has provider with the folowing table contailning sales data 
#1-use pandato lord the above table in to a data fram
#2 add the new col total remanue that calculate total remanue for eatch order 
#3 identify the best product/s 
import pandas as pd
data={"OrderId":[101,102,103,104,105],
                   "product":["capton","samosa","bobe","shampo","cuckis"],
                   "catogory":["Electric","Electric","Electric","Electric","Electric"],
                   "Quntity":[2,5,10,4,2],"Price":[1000,800,150,200,300]}
df = pd.DataFrame(data)
print(df)
print("====================")
df["total remanue"] = df["Quntity"]*df["Price"]
print(df)
print("===============")
best_product = df["total remanue"].max()
print("best product:",best_product)
print("=================")
filter = (df[df["total remanue"] == best_product])
print(filter)


   OrderId product  catogory  Quntity  Price
0      101  capton  Electric        2   1000
1      102  samosa  Electric        5    800
2      103    bobe  Electric       10    150
3      104  shampo  Electric        4    200
4      105  cuckis  Electric        2    300
   OrderId product  catogory  Quntity  Price  total remanue
0      101  capton  Electric        2   1000           2000
1      102  samosa  Electric        5    800           4000
2      103    bobe  Electric       10    150           1500
3      104  shampo  Electric        4    200            800
4      105  cuckis  Electric        2    300            600
best product: 4000
   OrderId product  catogory  Quntity  Price  total remanue
1      102  samosa  Electric        5    800           4000


In [170]:
#filtering
import pandas as pd
data = {
    "Name":["Alina","Dill","Till","Samith"],
    "Age":[22,23,55,45],
    "Score":[88,66,55,44]
}
df = pd.DataFrame(data)
print(df)
print("====================")
filter = df[df["Age"]>25]
print(filter)
print(type(filter))
print("================")
#sorting 
sorted_df = df.sort_values(by="Age")
print(sorted_df)


     Name  Age  Score
0   Alina   22     88
1    Dill   23     66
2    Till   55     55
3  Samith   45     44
     Name  Age  Score
2    Till   55     55
3  Samith   45     44
<class 'pandas.core.frame.DataFrame'>
     Name  Age  Score
0   Alina   22     88
1    Dill   23     66
3  Samith   45     44
2    Till   55     55
     Name  Score
0   Alina     88
1    Dill     66
2    Till     55
3  Samith     44


In [174]:
import pandas as pd
df = pd.read_csv('employees.csv')
print(df)
print(type(df))
print("=================")
df = pd.read_json('example_2.json')
print(df)

   EmployeeID   Name Department  Salary
0           1   John         IT   60000
1           2   Jane         HR   55000
2           3   Mike    Finance   70000
3           4  Linda         IT   65000
<class 'pandas.core.frame.DataFrame'>
                                                    quiz
sport  {'q1': {'question': 'Which one is correct team...
maths  {'q1': {'question': '5 + 7 = ?', 'options': ['...
