In [39]:
## moc Q & A
#01

import random
random_integer = random.randint(1, 100)
print(random_integer)


37


In [1]:
#06 - polymorphism

class Dog:
 def sound(self):
  print("bark")

class Cat:
 def sound(self):
  print("meow")


for animal in [Dog(),Cat()]:
 animal.sound()  

bark
meow


In [3]:
# Inheritance 
class Animal:
    def __init__(self,name):
     self.name = name

    def speak(self):
        return 'some sound'
     
class Dog(Animal):
   def speak(self):
      return "Bark" 

# create object
dog = Dog("Buddy")   
print(dog.name)
print(dog.speak())


Buddy
Bark


In [5]:
# Encapsulation

class BankAccount:
    def __init__(self,balance):
        self.__balance = balance

    def deposit(self,amount):
        self.__balance +=amount

    def get_balance(self):
        return self.__balance 

account = BankAccount(1000)
account.deposit(500)     
print(account.get_balance())      

1500


In [ ]:
# Abstraction

from abc import ABC, abstractmethod

class Animal(ABC):
    @abstractmethod
    def make_sound(self):
        pass
class Dog(Animal):
    def make_sound(self):
        return "Bark"
class Cat(Animal):
    def make_sound(self):
        return "Meow"
    
# Creating objects
dog = Dog()
cat = Cat()
print(dog.make_sound())  
print(cat.make_sound())  

Bark
Meow


In [13]:
# 10 filter data frame

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'Salary': [50000, 60000, 70000, 80000, 90000]
}

df = pd.DataFrame(data)
print(df)

print("===================")

# filter rows where age greater than 30

filtered_df = df[df['Age'] > 30]
print(filtered_df)

print("===================")

# Filter rows where Salary is less than 80000

finally_df = df[df['Salary']<8000]
print(filtered_df)

print("===================")

# Filter rows where Name is either 'Alice' or 'Eva'

filtered_df = df[df['Name'].isin(['Alice','Eva'])]
print(filtered_df)



      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    David   40   80000
4      Eva   45   90000
      Name  Age  Salary
2  Charlie   35   70000
3    David   40   80000
4      Eva   45   90000
      Name  Age  Salary
2  Charlie   35   70000
3    David   40   80000
4      Eva   45   90000
    Name  Age  Salary
0  Alice   25   50000
4    Eva   45   90000


In [ ]:

import pandas as pd

data = {
    'Color': ['Red','Blue','Black','Pink'],
}

df = pd.DataFrame(data)
print(df)

print('========================')

# Filter rows where Color is 'Red'

filtered_df = df[df['Color'] == 'Red']
print(filtered_df)

print('========================')

#Filter rows where Color starts with 'B'

filtered_df = df[df['Color'].str.startswith('B')]
print(filtered_df)

print('========================')

#Filter rows where Color contains 'Blue'

filtered_df =df[df['Color'].str.contains('Pink')]
print(filtered_df)

   Color
0    Red
1   Blue
2  Black
3   Pink
  Color
0   Red
   Color
1   Blue
2  Black
  Color
3  Pink


In [1]:
# data fram methord 

import pandas as pd

data = {
    'A':[1,3,5,7],
    'B':[10,20,30,40]
}

df = pd.DataFrame(data)
print(df)

print('====================')
# 01 shape
print("shape:",df.shape)

print('====================')
# 02 dtype
print("dtype:",df.dtypes)

print('====================')
# 03 size
print("size:",df.size)

print('====================')
# 04 value
print(df.values)

print('====================')
# 05 len
print("len:",len(df))

print('====================')
# 06 mean
print("mean:",df.mean())

print('====================')
# 07 sum
print("sum:",df.sum())

print('====================')
# 08 describe
print("describe:",df.describe)





   A   B
0  1  10
1  3  20
2  5  30
3  7  40
shape: (4, 2)
dtype: A    int64
B    int64
dtype: object
size: 8
[[ 1 10]
 [ 3 20]
 [ 5 30]
 [ 7 40]]
len: 4
mean: A     4.0
B    25.0
dtype: float64
sum: A     16
B    100
dtype: int64
describe: <bound method NDFrame.describe of    A   B
0  1  10
1  3  20
2  5  30
3  7  40>


In [2]:
# Q- B -short answer 
# 01 = n integer  nam true nathnam false n == 3^x 
def is_power_of_three(n):
    if n <= 0:
        return False
    while n % 3 == 0:
        n = n // 3
    return n == 1

print(is_power_of_three(27)) 
print(is_power_of_three(81))  
print(is_power_of_three(45)) 
print(is_power_of_three(0))


True
True
False
False


In [ ]:
#  CSV File Validation

import csv

file_path = 'python-moc.csv'

def find_invalid_entries(file_path):
    invalid_entries = []

    try:
        with open(file_path, 'r') as file:
            reader = csv.reader(file)
            next(reader)  # Skip the header row
            for line_num, row in enumerate(reader, 2):  # Start line numbering from 2
                # Check if the row has at least 2 columns (Timestamp and Temperature)
                if len(row) < 2:
                    invalid_entries.append((line_num, row))  # Store line number and row
                    continue

                # Check if the temperature value is a valid number
                try:
                    float(row[1])  # Attempt to convert temperature to float
                except ValueError:
                    invalid_entries.append((line_num, row))  # Store line number and row
    except FileNotFoundError:
        print(f"Error: The file '{file_path}' was not found.")
        return []
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return []

    return invalid_entries

# Example usage
invalid_entries = find_invalid_entries(file_path)
if invalid_entries:
    print("Invalid entries found:")
    for line_num, row in invalid_entries:
        print(f"Line {line_num}: {row}")
else:
    print("All entries are valid.")

All entries are valid.


In [ ]:
import csv

file_path = 'python-moc.csv'

def find_invalid_entries(file_path):
    invalid_lines = []
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        for line_num, row in enumerate(reader, 1):
            try:
                float(row[1])  # Check if temperature is a valid number
            except (ValueError, IndexError):
                invalid_lines.append(line_num)
    return invalid_lines

valide_temp = find_invalid_entries(file_path)
print(valide_temp)


[1]


In [ ]:
import numpy as np

def filter_temperatures(temp_array):
    # Filter temperatures >= 15°C and flatten the result
    return temp_array[temp_array >= 15].flatten()

# Example usage
# Create a sample temperature array for a week (7 days, 24 hours)
# Temperatures range from 10°C to 30°C

np.random.seed(42)  # For reproducibility
temp_array = np.random.randint(10, 31, size=(7, 24))

print("Original Temperature Array (7 days, 24 hours):")
print(temp_array)

# Filter temperatures >= 15°C
filtered_temps = filter_temperatures(temp_array)

print("\nFiltered Temperatures (>= 15°C):")
print(filtered_temps)

Original Temperature Array (7 days, 24 hours):
[[16 29 24 20 17 30 16 28 20 20 30 13 17 12 30 11 21 15 11 30 10 21 21 26]
 [19 25 24 24 28 21 29 12 14 28 16 30 18 16 27 13 23 27 18 30 11 29 24 16]
 [21 17 24 12 23 26 13 27 17 13 11 15 19 13 27 21 11 19 13 23 25 24 17 23]
 [17 30 25 22 27 24 30 22 18 24 22 10 16 18 10 21 17 20 28 26 17 12 12 10]
 [14 19 16 18 16 18 17 21 11 10 25 14 12 21 17 12 10 12 14 24 23 12 10 14]
 [23 16 18 24 24 19 22 28 16 26 29 13 14 16 22 24 20 13 22 16 28 11 19 22]
 [30 15 21 21 29 20 16 10 10 29 22 18 12 16 15 17 18 14 10 28 19 21 24 18]]

Filtered Temperatures (>= 15°C):
[16 29 24 20 17 30 16 28 20 20 30 17 30 21 15 30 21 21 26 19 25 24 24 28
 21 29 28 16 30 18 16 27 23 27 18 30 29 24 16 21 17 24 23 26 27 17 15 19
 27 21 19 23 25 24 17 23 17 30 25 22 27 24 30 22 18 24 22 16 18 21 17 20
 28 26 17 19 16 18 16 18 17 21 25 21 17 24 23 23 16 18 24 24 19 22 28 16
 26 29 16 22 24 20 22 16 28 19 22 30 15 21 21 29 20 16 29 22 18 16 15 17
 18 28 19 21 24 18]


In [35]:
import numpy as np

def filter_temperatures(temp_array):
    return temp_array[temp_array >= 15].flatten()

temp = filter_temperatures(temp_array)

print("\nFiltered Temperatures (>= 15°C):")
print(temp)


Filtered Temperatures (>= 15°C):
[16 29 24 20 17 30 16 28 20 20 30 17 30 21 15 30 21 21 26 19 25 24 24 28
 21 29 28 16 30 18 16 27 23 27 18 30 29 24 16 21 17 24 23 26 27 17 15 19
 27 21 19 23 25 24 17 23 17 30 25 22 27 24 30 22 18 24 22 16 18 21 17 20
 28 26 17 19 16 18 16 18 17 21 25 21 17 24 23 23 16 18 24 24 19 22 28 16
 26 29 16 22 24 20 22 16 28 19 22 30 15 21 21 29 20 16 29 22 18 16 15 17
 18 28 19 21 24 18]


In [2]:
import pandas as pd

# (i) Load CSV file
# Ensure the CSV file has columns: StudentID, Name, Subject, Score
df = pd.read_csv('student_scores.csv')

# Display the first few rows of the DataFrame
print("Original DataFrame:")
print(df)

# (ii) Calculate average score for each student
# Group by 'StudentID' and calculate the mean of 'Score' for each student
df['AverageScore'] = df.groupby('StudentID')['Score'].transform('mean')

# Display the DataFrame with the new 'AverageScore' column
print("\nDataFrame with Average Scores:")
print(df)

# (iii) Identify students with an average score >= 90
# Filter the DataFrame to include only students with an average score of 90 or above
top_students = df[df['AverageScore'] >= 90]

# Drop duplicates to show each student only once (since each student may have multiple rows)
top_students = top_students.drop_duplicates(subset=['StudentID'])

# Display the details of top students
print("\nTop Students with Average Score >= 90:")
print(top_students[['StudentID', 'Name', 'AverageScore']])

Original DataFrame:
   StudentID     Name  Subject  Score
0          1    Alice     Math     95
1          1    Alice  Science     90
2          2      Bob     Math     85
3          2      Bob  Science     80
4          3  Charlie     Math     92
5          3  Charlie  Science     94
6          4    David     Math     88
7          4    David  Science     89
8          5      Eva     Math     96
9          5      Eva  Science     97

DataFrame with Average Scores:
   StudentID     Name  Subject  Score  AverageScore
0          1    Alice     Math     95          92.5
1          1    Alice  Science     90          92.5
2          2      Bob     Math     85          82.5
3          2      Bob  Science     80          82.5
4          3  Charlie     Math     92          93.0
5          3  Charlie  Science     94          93.0
6          4    David     Math     88          88.5
7          4    David  Science     89          88.5
8          5      Eva     Math     96          96.5
9         

In [7]:
import pandas as pd

# (i) Load CSV file
df = pd.read_csv('student_scores.csv')

# (ii) Calculate average score
df['AverageScore'] = df.groupby('StudentID')['Score'].transform('mean')

# (iii) Identify students with average score >= 90
top_students = df[df['AverageScore'] >= 90]

print(top_students)

   StudentID     Name  Subject  Score  AverageScore
0          1    Alice     Math     95          92.5
1          1    Alice  Science     90          92.5
4          3  Charlie     Math     92          93.0
5          3  Charlie  Science     94          93.0
8          5      Eva     Math     96          96.5
9          5      Eva  Science     97          96.5


In [15]:
#Part C:
#Question 01: Library Management System

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def display_info(self):
        print(f"Name: {self.name}, Age: {self.age}")

class Librarian(Person):
    def __init__(self, name, age, employee_id):
        super().__init__(name, age)
        self.employee_id = employee_id

    def display_info(self):
        super().display_info()
        print(f"Employee ID: {self.employee_id}")

class Member(Person):
    def __init__(self, name, age, membership_id):
        super().__init__(name, age)
        self.membership_id = membership_id

    def display_info(self):
        super().display_info()
        print(f"Membership ID: {self.membership_id}")

class Library:
    def __init__(self):
        self._books = {}
        self._members = []

    def add_book(self, title, copies):
        self._books[title] = copies

    def register_member(self, member):
        self._members.append(member)

    def lend_book(self, title, member):
        if title in self._books and self._books[title] > 0:
            self._books[title] -= 1
            print(f"Book '{title}' lent to {member.name}")
        else:
            print(f"Book '{title}' not available")

    def show_all_books(self):
        for title, copies in self._books.items():
            print(f"Title: {title}, Copies: {copies}")

    def show_all_members(self):
        for member in self._members:
            member.display_info()

# Example usage
library = Library()
library.add_book("Python Programming", 5)
library.add_book("Data Science Handbook", 3)

member1 = Member("Alice", 25, "M001")
member2 = Member("Bob", 30, "M002")
library.register_member(member1)
library.register_member(member2)

library.lend_book("Python Programming", member1)
library.show_all_books()
library.show_all_members()


Book 'Python Programming' lent to Alice
Title: Python Programming, Copies: 4
Title: Data Science Handbook, Copies: 3
Name: Alice, Age: 25
Membership ID: M001
Name: Bob, Age: 30
Membership ID: M002


In [6]:
#Question 02: Employee Data Analysis

import pandas as pd
import numpy as np

# (a) Load dataset
df = pd.read_csv('employee_data.csv')
print(df.head())

print("=================================================")
# (b) Compute mean, median, and standard deviation of Salary
mean_salary = np.mean(df['Salary'])
median_salary = np.median(df['Salary'])
std_salary = np.std(df['Salary'])
print(f"Mean Salary: {mean_salary}, Median Salary: {median_salary}, Std Salary: {std_salary}")

print("=================================================")
# (c) Employees with ExperienceYears > 10
experienced_employees = df[df['ExperienceYears'] > 10]
print(f"Total experienced employees: {len(experienced_employees)}")

print("================================================")
# (d) Five highest-paid employees
top_earners = df.nlargest(5, 'Salary')
print(top_earners)

print("================================================")
# (e) Percentage of employees aged above 50
above_50 = df[df['Age'] > 50]
percentage = (len(above_50) / len(df)) * 100
print(f"Percentage of employees above 50: {percentage}%")

print("================================================")
# (f) Add ExperiencedLevel column
df['ExperiencedLevel'] = np.where(
    df['ExperienceYears'] >= 15, 'Senior',
    np.where(df['ExperienceYears'] >= 5, 'Mid-Level', 'Junior')
)

# (g) Sort by ExperiencedLevel and Salary
df_sorted = df.sort_values(by=['ExperiencedLevel', 'Salary'], ascending=[False, False])
print(df_sorted)

   EmployeeID  Age   Salary   Department  ExperienceYears
0           1   45  75000.0           HR               12
1           2   38  82000.0  Engineering                8
2           3   52  95000.0      Finance               20
3           4   29  60000.0    Marketing                4
4           5   41  88000.0  Engineering               10
Mean Salary: 82100.0, Median Salary: 85000.0, Std Salary: 15597.756248896827
Total experienced employees: 5
   EmployeeID  Age    Salary   Department  ExperienceYears
5           6   56  105000.0      Finance               25
9          10   50   98000.0      Finance               18
2           3   52   95000.0      Finance               20
7           8   48   91000.0  Engineering               15
4           5   41   88000.0  Engineering               10
Percentage of employees above 50: 20.0%
   EmployeeID  Age    Salary   Department  ExperienceYears ExperiencedLevel
5           6   56  105000.0      Finance               25           Senio

In [ ]:
#Question 03: Financial Data Retrieval
#(a) Web Scraping

import requests
from bs4 import BeautifulSoup

url = "https://example.com/market"
response = requests.get(url)

soup = BeautifulSoup(response.content, 'html.parser')

company_name = soup.find('h2', class_='company-name').text
ticker = soup.find('p', class_='ticker').text
price = soup.find('span', class_='current-price').text

print(f"Company: {company_name}, Ticker: {ticker}, Price: {price}")

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [3]:
#(b) Error Handling in Web Scraping

try:
    response = requests.get(url)
    response.raise_for_status()  # Check for HTTP errors
    soup = BeautifulSoup(response.content, 'html.parser')

    company_name = soup.find('h2', class_='company-name')
    if company_name:
        print(f"Company: {company_name.text}")
    else:
        print("Company name not found")
except requests.exceptions.RequestException as e:
    print(f"Error: {e}")

    

: 

In [4]:
#(C) API Integration
import requests

url = "https://api.example.com/market"
response = requests.get(url)
data = response.json()

for stock in data:
    print(f"Company: {stock['company']}, Ticker: {stock['ticker']}, Price: {stock['price']}")

ConnectionError: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /market (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002219A9F0550>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))